version: "3.3"
services:
  app:
    image: timetable:latest
    #    build:
    #      context: .
    container_name: app
    depends_on:
      - postgres
    environment:
      - APP_SCHEDULED_TIME=3600000
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/timetable
      - SPRING_DATASOURCE_USERNAME=app
      - SPRING_DATASOURCE_PASSWORD=veryha1337rdpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
  app2:
    image: timetable-bot:latest
    container_name: app2
    depends_on:
      - app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/timetable
      - SPRING_DATASOURCE_USERNAME=app
      - SPRING_DATASOURCE_PASSWORD=veryha1337rdpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - TELEGRAM_TOKEN=
    ports:
      - "8080:8080"
      - "80:80"
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "timetable"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "veryha1337rdpass"
    ports:
      - "5432:5432"
