version: "3.3"
services:
  app:
    image: ouiuo/timetable:0.6
#    build:
#      context: .
    container_name: app
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/timetable
      - SPRING_DATASOURCE_USERNAME=app
      - SPRING_DATASOURCE_PASSWORD=veryha1337rdpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "timetable"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "veryha1337rdpass"
    ports:
      - "5432:5432"
