version: "3.3"
services:
  app:
    image: timetable:latest
    #    build:
    #      context: .
    container_name: app
    depends_on:
      - postgres
    environment:
      - APP_SCHEDULED_TIMETABLE_TIME=3600000
      - APP_SCHEDULED_GROUPS_TIME=0 0 1 * * 1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/timetable
      - SPRING_DATASOURCE_USERNAME=app
      - SPRING_DATASOURCE_PASSWORD=veryha1337rdpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  app2:
    image: timetable-bot:latest
    container_name: app2
    depends_on:
      - app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/timetable
      - SPRING_DATASOURCE_USERNAME=app
      - SPRING_DATASOURCE_PASSWORD=veryha1337rdpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - TELEGRAM_TOKEN=5985520973:AAHK_YUQc70bYFDl6_VpqwslQLMpfZ-ifRQ
    ports:
      - "8080:8080"
      - "80:80"
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "timetable"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "veryha1337rdpass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /var/lib/postgresql/timetable:/var/lib/postgresql/data
    ports:
      - "5432:5432"
